### PR TITLE
Fixed #5: Make it work with Django 1.8 

### LINKED ISSUE #5: Django 1.8 support
I can't get this to work with Django 1.8. It throws a "no such option --settings" error.

Any ideas?

### PR DESCRIPTION
**Pull request by pcraston**
Django 1.8 no longer supports OptionParser. Use use_argparse to determine which Parser to use.

Does this PR make sense to you?

### CODE REVIEW

**Comment by saippuakauppias** [comment]
Hello!
You are tested this changes on django 1.5/1.6?

**Comment by pcraston** [comment]
Hi. The ```self.use_argparse``` should be false for previous versions of Django so that it should fall back to the previous behaviour.

Do you have any projects running django 1.5 or 1.6 where you could test this?

**Comment by saippuakauppias** [comment]
Only on django 1.3, but this is very old project, many developers not use now this version on production.

**Comment by pcraston** [comment]
Django BaseCommand uses the same syntax (```self.use_argparse```) to maintain backwards compatibility:
https://github.com/django/django/blob/master/django/core/management/base.py#L337

If ```use_argparse``` is false (previous Django versions) it just falls back to your previous behaviour, if it is true it uses the new behaviour.

**Comment by pcraston** [comment]
We've been running this fork on production with Django 1.8 for a week now, no problems. Older versions of Django should work as before.

**Comment by saippuakauppias** [comment]
Package on pypi updated.

**Comment by skorokithakis** [comment]
Maven crashes for me on 1.7.3:

```
Traceback (most recent call last):
  File "/var/projects/tithess/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/projects/tithess/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/projects/tithess/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/projects/tithess/env/local/lib/python2.7/site-packages/django_maven/management/commands/maven.py", line 52, in run_from_argv
    parser = self.create_parser(argv[0], argv[2], subcommand_class)
  File "/var/projects/tithess/env/local/lib/python2.7/site-packages/django_maven/management/commands/maven.py", line 38, in create_parser
    if not self.use_argparse:
AttributeError: 'Command' object has no attribute 'use_argparse'
```

**Comment by skorokithakis** [comment]
Yeah, this option was added in 1.8c1, it seems?:

https://github.com/django/django/commit/856863860352aa1f0288e6c9168a0e423c4f5184

**Comment by Altaisoft** [comment]
Crashing on Django 1.7.2. Replacing `self.use_argparse` by `getattr(self, 'use_argparse', False)` seems to do the trick.

**Pull request merged**
